<?php

use Illuminate\Database\Seeder;

class TournoiTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tournoi')->insert([
            'titre' => 'Oeuf de pâque',
            'imageUri' => 'dofus.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 200,
            'prix_inscription' => 100,
            'heureDebut' => '11:00',
            'event_id_event' => 3,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 3,
            'type_tournoi_id_type_tournoi' => 2,
            'page_twitter_url'=>'https://twitter.com/Warcraft',
            'page_facebook_url'=>'https://www.facebook.com/WorldofWarcraft.de/?brand_redir=184466263718',
            'page_youtube_url'=>'https://www.youtube.com/user/WorldofWarcraft',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/World%20of%20Warcraft',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Coupe Etoile Arc-En-Ciel',
            'imageUri' => 'marioKart.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 12,
            'prix_inscription' => 100,
            'heureDebut' => '12:00',
            'event_id_event' => 2,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 2,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/search?q=%23mariokart',
            'page_facebook_url'=>'https://www.facebook.com/MarioKartDE/?brand_redir=641705949306617',
            'page_youtube_url'=>'https://www.youtube.com/watch?v=1dMAe_6dwDs',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Mario%20Kart%208',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Gran Turismo',
            'imageUri' => 'granTurismo.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '10:00',
            'event_id_event' => 2,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 15,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/DOFUSfr',
            'page_facebook_url'=>'https://www.facebook.com/DOFUS/',
            'page_youtube_url'=>'https://www.youtube.com/user/dofus',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Dofus',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Libère ton talent dans PUBG !',
            'imageUri' => 'pubg.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 50,
            'prix_inscription' => 100,
            'heureDebut' => '13:00',
            'event_id_event' => 1,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 4,
            'type_tournoi_id_type_tournoi' => 2,
            'page_twitter_url'=>'https://twitter.com/PUBG',
            'page_facebook_url'=>'https://www.facebook.com/gaming/playerunknownsbattlegrounds/?sub_view=videos&fbsource=1103&external_ref=game_search_unit',
            'page_youtube_url'=>'https://www.youtube.com/channel/UCT1d4QydLziQUmp_lqQirMQ',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/PLAYERUNKNOWN\'S%20BATTLEGROUNDS',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'FiFa',
            'imageUri' => 'fifa.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '09:00',
            'event_id_event' => 7,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 5,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/_BeFoot',
            'page_facebook_url'=>'https://www.facebook.com/easportsfifa.fr/',
            'page_youtube_url'=>'https://www.youtube.com/user/EAsportsfootball',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/FIFA%2018',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Tournoi BattleField 1',
            'imageUri' => 'battlefield1.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '10:00',
            'event_id_event' => 1,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 6,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/Battlefield',
            'page_facebook_url'=>'https://www.facebook.com/groups/Battlefield5/',
            'page_youtube_url'=>'https://www.youtube.com/user/Battlefield',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Battlefield%201',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Tournoi Halo 5',
            'imageUri' => 'halo5.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '16:00',
            'event_id_event' => 1,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 7,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/Halo',
            'page_facebook_url'=>'https://www.facebook.com/Fansdehalo5/',
            'page_youtube_url'=>'https://www.youtube.com/watch?v=v2uEb5Vrtwk',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Halo%205%3A%20Guardians',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Tournoi Fortnite',
            'imageUri' => 'fortnite.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '15:00',
            'event_id_event' => 1,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 8,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/FortniteGame',
            'page_facebook_url'=>'https://www.facebook.com/FortniteFRA/',
            'page_youtube_url'=>'https://www.youtube.com/channel/UCZDxHqJRVGXvWIxAjoVU0cg',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Fortnite',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Heroes of the Storm',
            'imageUri' => 'heroesOfTheStorm.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '20:00',
            'event_id_event' => 5,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 9,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/BlizzHeroes',
            'page_facebook_url'=>'https://www.facebook.com/heroesofthestorm.de/?brand_redir=526330610781529',
            'page_youtube_url'=>'https://www.youtube.com/user/BlizzHeroes',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Heroes%20of%20the%20Storm',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Tournoi de LOL',
            'imageUri' => 'leagueOfLegends.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '21:00',
            'event_id_event' => 5,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 10,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/LeagueOfLegends',
            'page_facebook_url'=>'https://www.facebook.com/leagueoflegends/',
            'page_youtube_url'=>'https://www.youtube.com/user/RiotGamesInc',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/League%20of%20Legends',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Tournoi CS',
            'imageUri' => 'cs.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 2,
            'prix_inscription' => 100,
            'heureDebut' => '17:00',
            'event_id_event' => 1,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 11,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/ESLCS',
            'page_facebook_url'=>'https://www.facebook.com/CounterStrike/?ref=br_rs',
            'page_youtube_url'=>'https://www.youtube.com/channel/UC00V7qiby55raDY3LVHBS5Q',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Counter-Strike%3A%20Global%20Offensive',
            'msg_partage'=>'',
        ]);
        DB::table('tournoi')->insert([
            'titre' => 'Tournoi World of Warcraft',
            'imageUri' => 'wow.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'reglementUri' => 'go.pdf',
            'prix_inscription' => 100,
            'heureDebut' => '16:30',
            'event_id_event' => 3,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 11,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/Warcraft',
            'page_facebook_url'=>'https://www.facebook.com/WorldofWarcraft.de/?brand_redir=184466263718',
            'page_youtube_url'=>'https://www.youtube.com/user/WorldofWarcraft',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/World%20of%20Warcraft',
            'msg_partage'=>'',
        ]);

        DB::table('tournoi')->insert([
            'titre' => 'Tournoi Tekken',
            'imageUri' => 'tekken.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '08:45',
            'reglementUri' => 'go.pdf',
            'event_id_event' => 4,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 11,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/search?q=%23mariokart',
            'page_facebook_url'=>'https://www.facebook.com/MarioKartDE/?brand_redir=641705949306617',
            'page_youtube_url'=>'https://www.youtube.com/watch?v=1dMAe_6dwDs',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Mario%20Kart%208',
            'msg_partage'=>'',
        ]);

        DB::table('tournoi')->insert([
            'titre' => 'Tournoi Soulcalibur',
            'imageUri' => 'soulcalibur.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '12:45',
            'reglementUri' => 'go.pdf',
            'event_id_event' => 4,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 11,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/search?q=%23mariokart',
            'page_facebook_url'=>'https://www.facebook.com/MarioKartDE/?brand_redir=641705949306617',
            'page_youtube_url'=>'https://www.youtube.com/watch?v=1dMAe_6dwDs',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Mario%20Kart%208',
            'msg_partage'=>'',
        ]);

        DB::table('tournoi')->insert([
            'titre' => 'Tournoi World of Warcraft',
            'imageUri' => 'wow.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'reglementUri' => 'go.pdf',
            'prix_inscription' => 100,
            'heureDebut' => '16:30',
            'event_id_event' => 6,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 11,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/Warcraft',
            'page_facebook_url'=>'https://www.facebook.com/WorldofWarcraft.de/?brand_redir=184466263718',
            'page_youtube_url'=>'https://www.youtube.com/user/WorldofWarcraft',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/World%20of%20Warcraft',
            'msg_partage'=>'',
        ]);

        DB::table('tournoi')->insert([
            'titre' => 'Tournoi CS',
            'imageUri' => 'cs.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 2,
            'prix_inscription' => 100,
            'heureDebut' => '17:00',
            'event_id_event' => 6,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 11,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/ESLCS',
            'page_facebook_url'=>'https://www.facebook.com/CounterStrike/?ref=br_rs',
            'page_youtube_url'=>'https://www.youtube.com/channel/UC00V7qiby55raDY3LVHBS5Q',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Counter-Strike%3A%20Global%20Offensive',
            'msg_partage'=>'',
        ]);

        DB::table('tournoi')->insert([
            'titre' => 'Tournoi MarioKart',
            'imageUri' => 'marioKart.jpg',
            'description' => 'Voici le tout nouveau tournoi organisé par ton bar E-Sport préféré ! Le RedCloud bien sûr ! Si tu penses être assez puissant pour battre tous tes amis et ennemis, alors tu dois impérativement t\'inscrire à ce tournoi et nous prouver ta valeur. Tu trouveras toutes les informations concernant la règlementation de ce tournoi dans le fichier pdf ci-dessous. Et toutes les infos concernant la liste des équipes participantes ou le prix d\'inscription, par exemple, sont affichées à la fin de cette page de tournoi. Nous t\'attendons avec impatience au bar et que la force soit avec toi !',
            'participants_max' => 20,
            'prix_inscription' => 100,
            'heureDebut' => '15:45',
            'reglementUri' => 'go.pdf',
            'event_id_event' => 6,
            'reglementUri' => 'go.pdf',
            'jeu_id_jeu' => 11,
            'type_tournoi_id_type_tournoi' => 1,
            'page_twitter_url'=>'https://twitter.com/search?q=%23mariokart',
            'page_facebook_url'=>'https://www.facebook.com/MarioKartDE/?brand_redir=641705949306617',
            'page_youtube_url'=>'https://www.youtube.com/watch?v=1dMAe_6dwDs',
            'page_twitch_url'=>'https://www.twitch.tv/directory/game/Mario%20Kart%208',
            'msg_partage'=>'',
        ]);
    }
}
